# Generated by Django 6.0.4 on 2026-04-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='solutions/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('invalide', 'Invalide'), ('en_cours', 'En cours')], default='en_cours', max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('message_checker', models.TextField(blank=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipes.equipe')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.instance')),
            ],
            options={
                'unique_together': {('equipe', 'instance')},
            },
        ),
    ]
