# Generated by Django 6.0.4 on 2026-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='message_checker',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='statut',
        ),
        migrations.AddField(
            model_name='instance',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='solutions/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
