# Generated by Django 6.0.4 on 2026-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_remove_solution_message_checker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
